# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-06 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email_bool',
            field=models.BooleanField(default=False, verbose_name='send_email'),
        ),
    ]
