# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0003_auto_20160306_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email_body',
            field=models.TextField(default='Dear [first name] [last_name],\n\nHappy birthday!\n\nSincerly,\n{0}'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_subject',
            field=models.CharField(default='Happy birthday from {0}', max_length=256),
        ),
    ]
