# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0004_auto_20160306_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email_body',
            field=models.TextField(default='Dear [first name] [last_name],\n\nHappy birthday!\n\nSincerely,\n{0}'),
        ),
    ]
