# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0005_auto_20160306_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email_bool',
            field=models.BooleanField(),
        ),
    ]
