# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0007_auto_20160306_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email_body',
            field=models.TextField(default='Dear [first name] [last name],\n\nHappy birthday!\n\nSincerely,\nDr. {0}'),
        ),
    ]
