# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_reminder', '0008_auto_20160308_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email_subject',
            field=models.CharField(default='Happy birthday from Dr. {0}', max_length=256),
        ),
    ]
