# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drchrono_birthdays', '0003_auto_20160306_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email_bool',
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_body',
            field=models.TextField(default='Dear [first name] [last name],\n\nHappy birthday!\n\nSincerely,\nDr. {0}'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email_subject',
            field=models.CharField(default='Happy birthday from Dr. {0}', max_length=256),
        ),
        migrations.AddField(
            model_name='patient',
            name='send_email',
            field=models.BooleanField(default=False),
        ),
    ]
